<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RENLTP2N103" failures="12" tests="25" name="EmployeesAPI Automation" time="14.331" errors="0" timestamp="2022-01-24T19:15:13 IST">
  <testcase classname="com.employeeapi.testcases.GetAllEmployees_TC_001" name="checkHeaderContent" time="0.026"/>
  <testcase classname="com.employeeapi.testcases.GetAllEmployees_TC_001" name="checkResponseBody" time="0.03"/>
  <testcase classname="com.employeeapi.testcases.GetAllEmployees_TC_001" name="checkResponseTime" time="0.002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.employeeapi.testcases.GetAllEmployees_TC_001.checkResponseTime(GetAllEmployees_TC_001.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseTime -->
  <testcase classname="com.employeeapi.testcases.GetAllEmployees_TC_001" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.employeeapi.testcases.GetAllEmployees_TC_001" name="checkSucessMessage" time="0.609"/>
  <testcase classname="com.employeeapi.testcases.GetEmployeeByID_TC_002" name="checkResponseBody" time="0.012"/>
  <testcase classname="com.employeeapi.testcases.GetEmployeeByID_TC_002" name="checkResponseTime" time="0.003"/>
  <testcase classname="com.employeeapi.testcases.GetEmployeeByID_TC_002" name="checkStatusCode" time="0.003">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;429&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at org.junit.Assert.assertEquals(Assert.java:456)
at com.employeeapi.testcases.GetEmployeeByID_TC_002.checkStatusCode(GetEmployeeByID_TC_002.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcases.PostCreateEmployee_TC_003" name="checkHeaderType" time="0.013"/>
  <testcase classname="com.employeeapi.testcases.PostCreateEmployee_TC_003" name="checkResponseBody" time="0.005"/>
  <testcase classname="com.employeeapi.testcases.PostCreateEmployee_TC_003" name="checkStatusCode" time="0.003"/>
  <testcase classname="com.employeeapi.testcases.PostCreateEmployee_TC_003" name="checkStatusLine" time="0.003"/>
  <testcase classname="com.employeeapi.testcases.PostCreateEmployee_TC_003" name="tearDown" time="0.003"/>
  <testcase classname="com.employeeapi.testcases.UpdateEmployeeRecord_TC_004" name="checkHeaderType" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testcases.UpdateEmployeeRecord_TC_004.checkHeaderType(UpdateEmployeeRecord_TC_004.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkHeaderType -->
  <testcase classname="com.employeeapi.testcases.UpdateEmployeeRecord_TC_004" name="checkMessage" time="0.008">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testcases.UpdateEmployeeRecord_TC_004.checkMessage(UpdateEmployeeRecord_TC_004.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 32 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkMessage -->
  <testcase classname="com.employeeapi.testcases.UpdateEmployeeRecord_TC_004" name="checkResponseBody" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcases.UpdateEmployeeRecord_TC_004.checkResponseBody(UpdateEmployeeRecord_TC_004.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapi.testcases.UpdateEmployeeRecord_TC_004" name="checkStatusCode" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcases.UpdateEmployeeRecord_TC_004.checkStatusCode(UpdateEmployeeRecord_TC_004.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcases.UpdateEmployeeRecord_TC_004" name="checkStatusLine" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcases.UpdateEmployeeRecord_TC_004.checkStatusLine(UpdateEmployeeRecord_TC_004.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employeeapi.testcases.UpdateEmployeeRecord_TC_004" name="tearDown" time="0.001"/>
  <testcase classname="com.employeeapi.testcases.DeleteEmployeeRecord_TC_005" name="checkHeaderType" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testcases.DeleteEmployeeRecord_TC_005.checkHeaderType(DeleteEmployeeRecord_TC_005.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkHeaderType -->
  <testcase classname="com.employeeapi.testcases.DeleteEmployeeRecord_TC_005" name="checkMessage" time="0.005">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testcases.DeleteEmployeeRecord_TC_005.checkMessage(DeleteEmployeeRecord_TC_005.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 32 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkMessage -->
  <testcase classname="com.employeeapi.testcases.DeleteEmployeeRecord_TC_005" name="checkResponseBody" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testcases.DeleteEmployeeRecord_TC_005.checkResponseBody(DeleteEmployeeRecord_TC_005.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapi.testcases.DeleteEmployeeRecord_TC_005" name="checkStatusCode" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testcases.DeleteEmployeeRecord_TC_005.checkStatusCode(DeleteEmployeeRecord_TC_005.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.employeeapi.testcases.DeleteEmployeeRecord_TC_005" name="checkStatusLine" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testcases.DeleteEmployeeRecord_TC_005.checkStatusLine(DeleteEmployeeRecord_TC_005.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.employeeapi.testcases.DeleteEmployeeRecord_TC_005" name="tearDown" time="0.004"/>
</testsuite> <!-- EmployeesAPI Automation -->
